# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Daniel/Documents/Projects/mangaupdates

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Daniel/Documents/Projects/mangaupdates

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Daniel/Documents/Projects/mangaupdates/CMakeFiles /home/Daniel/Documents/Projects/mangaupdates//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Daniel/Documents/Projects/mangaupdates/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MangaUpdates

# Build rule for target.
MangaUpdates: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MangaUpdates
.PHONY : MangaUpdates

# fast build rule for target.
MangaUpdates/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/build
.PHONY : MangaUpdates/fast

CommandManager.o: CommandManager.cpp.o
.PHONY : CommandManager.o

# target to build an object file
CommandManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/CommandManager.cpp.o
.PHONY : CommandManager.cpp.o

CommandManager.i: CommandManager.cpp.i
.PHONY : CommandManager.i

# target to preprocess a source file
CommandManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/CommandManager.cpp.i
.PHONY : CommandManager.cpp.i

CommandManager.s: CommandManager.cpp.s
.PHONY : CommandManager.s

# target to generate assembly for a file
CommandManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/CommandManager.cpp.s
.PHONY : CommandManager.cpp.s

commands/BaseCommand.o: commands/BaseCommand.cpp.o
.PHONY : commands/BaseCommand.o

# target to build an object file
commands/BaseCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/commands/BaseCommand.cpp.o
.PHONY : commands/BaseCommand.cpp.o

commands/BaseCommand.i: commands/BaseCommand.cpp.i
.PHONY : commands/BaseCommand.i

# target to preprocess a source file
commands/BaseCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/commands/BaseCommand.cpp.i
.PHONY : commands/BaseCommand.cpp.i

commands/BaseCommand.s: commands/BaseCommand.cpp.s
.PHONY : commands/BaseCommand.s

# target to generate assembly for a file
commands/BaseCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/commands/BaseCommand.cpp.s
.PHONY : commands/BaseCommand.cpp.s

commands/LatestCommand.o: commands/LatestCommand.cpp.o
.PHONY : commands/LatestCommand.o

# target to build an object file
commands/LatestCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/commands/LatestCommand.cpp.o
.PHONY : commands/LatestCommand.cpp.o

commands/LatestCommand.i: commands/LatestCommand.cpp.i
.PHONY : commands/LatestCommand.i

# target to preprocess a source file
commands/LatestCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/commands/LatestCommand.cpp.i
.PHONY : commands/LatestCommand.cpp.i

commands/LatestCommand.s: commands/LatestCommand.cpp.s
.PHONY : commands/LatestCommand.s

# target to generate assembly for a file
commands/LatestCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/commands/LatestCommand.cpp.s
.PHONY : commands/LatestCommand.cpp.s

commands/SetCommand.o: commands/SetCommand.cpp.o
.PHONY : commands/SetCommand.o

# target to build an object file
commands/SetCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/commands/SetCommand.cpp.o
.PHONY : commands/SetCommand.cpp.o

commands/SetCommand.i: commands/SetCommand.cpp.i
.PHONY : commands/SetCommand.i

# target to preprocess a source file
commands/SetCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/commands/SetCommand.cpp.i
.PHONY : commands/SetCommand.cpp.i

commands/SetCommand.s: commands/SetCommand.cpp.s
.PHONY : commands/SetCommand.s

# target to generate assembly for a file
commands/SetCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/commands/SetCommand.cpp.s
.PHONY : commands/SetCommand.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/main.cpp.s
.PHONY : main.cpp.s

utils/CSVGateway.o: utils/CSVGateway.cpp.o
.PHONY : utils/CSVGateway.o

# target to build an object file
utils/CSVGateway.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/utils/CSVGateway.cpp.o
.PHONY : utils/CSVGateway.cpp.o

utils/CSVGateway.i: utils/CSVGateway.cpp.i
.PHONY : utils/CSVGateway.i

# target to preprocess a source file
utils/CSVGateway.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/utils/CSVGateway.cpp.i
.PHONY : utils/CSVGateway.cpp.i

utils/CSVGateway.s: utils/CSVGateway.cpp.s
.PHONY : utils/CSVGateway.s

# target to generate assembly for a file
utils/CSVGateway.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/utils/CSVGateway.cpp.s
.PHONY : utils/CSVGateway.cpp.s

utils/MangaUpdatesGateway.o: utils/MangaUpdatesGateway.cpp.o
.PHONY : utils/MangaUpdatesGateway.o

# target to build an object file
utils/MangaUpdatesGateway.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/utils/MangaUpdatesGateway.cpp.o
.PHONY : utils/MangaUpdatesGateway.cpp.o

utils/MangaUpdatesGateway.i: utils/MangaUpdatesGateway.cpp.i
.PHONY : utils/MangaUpdatesGateway.i

# target to preprocess a source file
utils/MangaUpdatesGateway.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/utils/MangaUpdatesGateway.cpp.i
.PHONY : utils/MangaUpdatesGateway.cpp.i

utils/MangaUpdatesGateway.s: utils/MangaUpdatesGateway.cpp.s
.PHONY : utils/MangaUpdatesGateway.s

# target to generate assembly for a file
utils/MangaUpdatesGateway.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/utils/MangaUpdatesGateway.cpp.s
.PHONY : utils/MangaUpdatesGateway.cpp.s

utils/Memory.o: utils/Memory.cpp.o
.PHONY : utils/Memory.o

# target to build an object file
utils/Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/utils/Memory.cpp.o
.PHONY : utils/Memory.cpp.o

utils/Memory.i: utils/Memory.cpp.i
.PHONY : utils/Memory.i

# target to preprocess a source file
utils/Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/utils/Memory.cpp.i
.PHONY : utils/Memory.cpp.i

utils/Memory.s: utils/Memory.cpp.s
.PHONY : utils/Memory.s

# target to generate assembly for a file
utils/Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/utils/Memory.cpp.s
.PHONY : utils/Memory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MangaUpdates"
	@echo "... CommandManager.o"
	@echo "... CommandManager.i"
	@echo "... CommandManager.s"
	@echo "... commands/BaseCommand.o"
	@echo "... commands/BaseCommand.i"
	@echo "... commands/BaseCommand.s"
	@echo "... commands/LatestCommand.o"
	@echo "... commands/LatestCommand.i"
	@echo "... commands/LatestCommand.s"
	@echo "... commands/SetCommand.o"
	@echo "... commands/SetCommand.i"
	@echo "... commands/SetCommand.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils/CSVGateway.o"
	@echo "... utils/CSVGateway.i"
	@echo "... utils/CSVGateway.s"
	@echo "... utils/MangaUpdatesGateway.o"
	@echo "... utils/MangaUpdatesGateway.i"
	@echo "... utils/MangaUpdatesGateway.s"
	@echo "... utils/Memory.o"
	@echo "... utils/Memory.i"
	@echo "... utils/Memory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

