# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Daniel/Documents/Projects/mangaupdates

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Daniel/Documents/Projects/mangaupdates

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Daniel/Documents/Projects/mangaupdates/CMakeFiles /home/Daniel/Documents/Projects/mangaupdates//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Daniel/Documents/Projects/mangaupdates/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MangaUpdates

# Build rule for target.
MangaUpdates: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MangaUpdates
.PHONY : MangaUpdates

# fast build rule for target.
MangaUpdates/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/build
.PHONY : MangaUpdates/fast

#=============================================================================
# Target rules for targets named MangaUpdatesTest

# Build rule for target.
MangaUpdatesTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MangaUpdatesTest
.PHONY : MangaUpdatesTest

# fast build rule for target.
MangaUpdatesTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/build
.PHONY : MangaUpdatesTest/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/CommandManager.o: src/CommandManager.cpp.o
.PHONY : src/CommandManager.o

# target to build an object file
src/CommandManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/CommandManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/CommandManager.cpp.o
.PHONY : src/CommandManager.cpp.o

src/CommandManager.i: src/CommandManager.cpp.i
.PHONY : src/CommandManager.i

# target to preprocess a source file
src/CommandManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/CommandManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/CommandManager.cpp.i
.PHONY : src/CommandManager.cpp.i

src/CommandManager.s: src/CommandManager.cpp.s
.PHONY : src/CommandManager.s

# target to generate assembly for a file
src/CommandManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/CommandManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/CommandManager.cpp.s
.PHONY : src/CommandManager.cpp.s

src/commands/BaseCommand.o: src/commands/BaseCommand.cpp.o
.PHONY : src/commands/BaseCommand.o

# target to build an object file
src/commands/BaseCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/commands/BaseCommand.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/commands/BaseCommand.cpp.o
.PHONY : src/commands/BaseCommand.cpp.o

src/commands/BaseCommand.i: src/commands/BaseCommand.cpp.i
.PHONY : src/commands/BaseCommand.i

# target to preprocess a source file
src/commands/BaseCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/commands/BaseCommand.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/commands/BaseCommand.cpp.i
.PHONY : src/commands/BaseCommand.cpp.i

src/commands/BaseCommand.s: src/commands/BaseCommand.cpp.s
.PHONY : src/commands/BaseCommand.s

# target to generate assembly for a file
src/commands/BaseCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/commands/BaseCommand.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/commands/BaseCommand.cpp.s
.PHONY : src/commands/BaseCommand.cpp.s

src/commands/LatestCommand.o: src/commands/LatestCommand.cpp.o
.PHONY : src/commands/LatestCommand.o

# target to build an object file
src/commands/LatestCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/commands/LatestCommand.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/commands/LatestCommand.cpp.o
.PHONY : src/commands/LatestCommand.cpp.o

src/commands/LatestCommand.i: src/commands/LatestCommand.cpp.i
.PHONY : src/commands/LatestCommand.i

# target to preprocess a source file
src/commands/LatestCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/commands/LatestCommand.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/commands/LatestCommand.cpp.i
.PHONY : src/commands/LatestCommand.cpp.i

src/commands/LatestCommand.s: src/commands/LatestCommand.cpp.s
.PHONY : src/commands/LatestCommand.s

# target to generate assembly for a file
src/commands/LatestCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/commands/LatestCommand.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/commands/LatestCommand.cpp.s
.PHONY : src/commands/LatestCommand.cpp.s

src/commands/SetCommand.o: src/commands/SetCommand.cpp.o
.PHONY : src/commands/SetCommand.o

# target to build an object file
src/commands/SetCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/commands/SetCommand.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/commands/SetCommand.cpp.o
.PHONY : src/commands/SetCommand.cpp.o

src/commands/SetCommand.i: src/commands/SetCommand.cpp.i
.PHONY : src/commands/SetCommand.i

# target to preprocess a source file
src/commands/SetCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/commands/SetCommand.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/commands/SetCommand.cpp.i
.PHONY : src/commands/SetCommand.cpp.i

src/commands/SetCommand.s: src/commands/SetCommand.cpp.s
.PHONY : src/commands/SetCommand.s

# target to generate assembly for a file
src/commands/SetCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/commands/SetCommand.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/commands/SetCommand.cpp.s
.PHONY : src/commands/SetCommand.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/CSVGateway.o: src/utils/CSVGateway.cpp.o
.PHONY : src/utils/CSVGateway.o

# target to build an object file
src/utils/CSVGateway.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/utils/CSVGateway.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/utils/CSVGateway.cpp.o
.PHONY : src/utils/CSVGateway.cpp.o

src/utils/CSVGateway.i: src/utils/CSVGateway.cpp.i
.PHONY : src/utils/CSVGateway.i

# target to preprocess a source file
src/utils/CSVGateway.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/utils/CSVGateway.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/utils/CSVGateway.cpp.i
.PHONY : src/utils/CSVGateway.cpp.i

src/utils/CSVGateway.s: src/utils/CSVGateway.cpp.s
.PHONY : src/utils/CSVGateway.s

# target to generate assembly for a file
src/utils/CSVGateway.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/utils/CSVGateway.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/utils/CSVGateway.cpp.s
.PHONY : src/utils/CSVGateway.cpp.s

src/utils/MangaUpdatesGateway.o: src/utils/MangaUpdatesGateway.cpp.o
.PHONY : src/utils/MangaUpdatesGateway.o

# target to build an object file
src/utils/MangaUpdatesGateway.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/utils/MangaUpdatesGateway.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/utils/MangaUpdatesGateway.cpp.o
.PHONY : src/utils/MangaUpdatesGateway.cpp.o

src/utils/MangaUpdatesGateway.i: src/utils/MangaUpdatesGateway.cpp.i
.PHONY : src/utils/MangaUpdatesGateway.i

# target to preprocess a source file
src/utils/MangaUpdatesGateway.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/utils/MangaUpdatesGateway.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/utils/MangaUpdatesGateway.cpp.i
.PHONY : src/utils/MangaUpdatesGateway.cpp.i

src/utils/MangaUpdatesGateway.s: src/utils/MangaUpdatesGateway.cpp.s
.PHONY : src/utils/MangaUpdatesGateway.s

# target to generate assembly for a file
src/utils/MangaUpdatesGateway.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/utils/MangaUpdatesGateway.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/utils/MangaUpdatesGateway.cpp.s
.PHONY : src/utils/MangaUpdatesGateway.cpp.s

src/utils/Memory.o: src/utils/Memory.cpp.o
.PHONY : src/utils/Memory.o

# target to build an object file
src/utils/Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/utils/Memory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/utils/Memory.cpp.o
.PHONY : src/utils/Memory.cpp.o

src/utils/Memory.i: src/utils/Memory.cpp.i
.PHONY : src/utils/Memory.i

# target to preprocess a source file
src/utils/Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/utils/Memory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/utils/Memory.cpp.i
.PHONY : src/utils/Memory.cpp.i

src/utils/Memory.s: src/utils/Memory.cpp.s
.PHONY : src/utils/Memory.s

# target to generate assembly for a file
src/utils/Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdates.dir/build.make CMakeFiles/MangaUpdates.dir/src/utils/Memory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/src/utils/Memory.cpp.s
.PHONY : src/utils/Memory.cpp.s

test/utils/MangaUpdatesGatewayTest.o: test/utils/MangaUpdatesGatewayTest.cpp.o
.PHONY : test/utils/MangaUpdatesGatewayTest.o

# target to build an object file
test/utils/MangaUpdatesGatewayTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/test/utils/MangaUpdatesGatewayTest.cpp.o
.PHONY : test/utils/MangaUpdatesGatewayTest.cpp.o

test/utils/MangaUpdatesGatewayTest.i: test/utils/MangaUpdatesGatewayTest.cpp.i
.PHONY : test/utils/MangaUpdatesGatewayTest.i

# target to preprocess a source file
test/utils/MangaUpdatesGatewayTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/test/utils/MangaUpdatesGatewayTest.cpp.i
.PHONY : test/utils/MangaUpdatesGatewayTest.cpp.i

test/utils/MangaUpdatesGatewayTest.s: test/utils/MangaUpdatesGatewayTest.cpp.s
.PHONY : test/utils/MangaUpdatesGatewayTest.s

# target to generate assembly for a file
test/utils/MangaUpdatesGatewayTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MangaUpdatesTest.dir/build.make CMakeFiles/MangaUpdatesTest.dir/test/utils/MangaUpdatesGatewayTest.cpp.s
.PHONY : test/utils/MangaUpdatesGatewayTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... MangaUpdates"
	@echo "... MangaUpdatesTest"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/CommandManager.o"
	@echo "... src/CommandManager.i"
	@echo "... src/CommandManager.s"
	@echo "... src/commands/BaseCommand.o"
	@echo "... src/commands/BaseCommand.i"
	@echo "... src/commands/BaseCommand.s"
	@echo "... src/commands/LatestCommand.o"
	@echo "... src/commands/LatestCommand.i"
	@echo "... src/commands/LatestCommand.s"
	@echo "... src/commands/SetCommand.o"
	@echo "... src/commands/SetCommand.i"
	@echo "... src/commands/SetCommand.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/CSVGateway.o"
	@echo "... src/utils/CSVGateway.i"
	@echo "... src/utils/CSVGateway.s"
	@echo "... src/utils/MangaUpdatesGateway.o"
	@echo "... src/utils/MangaUpdatesGateway.i"
	@echo "... src/utils/MangaUpdatesGateway.s"
	@echo "... src/utils/Memory.o"
	@echo "... src/utils/Memory.i"
	@echo "... src/utils/Memory.s"
	@echo "... test/utils/MangaUpdatesGatewayTest.o"
	@echo "... test/utils/MangaUpdatesGatewayTest.i"
	@echo "... test/utils/MangaUpdatesGatewayTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

